PRC-206 : Patch a contact
ministryofjustice/hmpps-contacts-api pull request #70
Opened 2024-10-17 11:09 UTC by prabash-moj

PRC-206 : Patch a contact

2024-10-17 14:01 UTC, james-baker-moj commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/patch/PatchContactRequest.kt
> +  val updatedTime: LocalDateTime? = null,
This should be set by the back end not in the request

2024-10-17 15:27 UTC, prabash-moj commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/patch/PatchContactEntityMappers.kt
> +fun ContactEntity.patchRequest(
It would make easier to unit test by extracting into a own unit, I also see the information hiding point of view it may not feel good to separate, 

This would also make extensible as we can extract individual field into its own mapper with validation etc?

2024-10-17 15:29 UTC, prabash-moj commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/patch/PatchContactRequest.kt
> +  val updatedTime: LocalDateTime? = null,
good catch, I was thinking about this but slipped it out,

2024-10-17 15:31 UTC, prabash-moj commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/patch/PatchContactRequest.kt
> +  var comments: String? = null,
will rebase and resolve

2024-10-21 14:14 UTC, prabash-moj commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/patch/PatchContactEntityMappers.kt
> +fun ContactEntity.patchRequest(
Moved into own unit to so it only perform patch action - with improved unit tests

2024-10-21 15:41 UTC, james-baker-moj requested changes

2024-10-21 15:41 UTC, james-baker-moj commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchContactIntegrationTest.kt
> +  fun `should successfully patch the updated by field when its the only field in the request`() {
I don't think this test is doing what it says its for. The language code starts as null, is set to null and is checked is null so it's not testing that language code is not changed.

2024-10-21 15:41 UTC, james-baker-moj commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchContactIntegrationTest.kt
> +  fun `should successfully patch the request`() {
This seems to be the same as `should successfully patch the contact with all fields`

2024-10-21 15:41 UTC, james-baker-moj commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
> +      title = this.title,
All these fields being set to themselves is quite confusing. Just set only language code instead as that's the only one that can actually be changed.

2024-10-21 15:41 UTC, james-baker-moj commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/patch/util/PatchableDeserializer.kt
> +    return if (node.isNull || node.isMissingNode) {
This looks wrong. We want nulls to be set to present surely?

2024-10-21 15:42 UTC, james-baker-moj commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchContactIntegrationTest.kt
> +
There should be a test where languageCode is set to a value and then set back to null

2024-10-22 13:15 UTC, prabash-moj commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchContactIntegrationTest.kt
> +  fun `should successfully patch the updated by field when its the only field in the request`() {
Confusion due to merging some tests - noticed an issue with json serialization from the integration tess, Have replaced with actual json object as a value, fixed those missing tests

2024-10-22 13:41 UTC, james-baker-moj commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
> +      title = this.title,
I thought you were going to remove the ones in the `copy`?

2024-10-22 13:42 UTC, james-baker-moj commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchContactIntegrationTest.kt
> +    setupTestApiClient()
I don't think you need to call this directly as it's already in a `@BeforeEach`

2024-10-22 13:46 UTC, prabash-moj commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
> +      title = this.title,
Ops , have moved this to its own sections but looks I have forgot to remove it from here, Removed all this now

2024-10-22 13:48 UTC, prabash-moj commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/patch/util/PatchableSerializer.kt
> +          }
This is partially only used in integration tests only, This need further digging to remove the field when the field is undefined, 
when null and value is present it is working as expected , there are integration tests to cover those scenarios too

2024-10-22 15:00 UTC, prabash-moj commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/patch/util/PatchableSerializer.kt
> +          }
Ok this is the tricky bit, this is only used in Integration tests, do not work as expected when serialise objects into json object when the  Patchable.undefined() case, other scenarios are fine, 

I will drop this now and use the import org.openapitools.jackson.nullable.JsonNullable instead of sealed classes, 
Its not worth the effort anymore unfortunately :(

2024-10-22 15:22 UTC, prabash-moj commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchContactIntegrationTest.kt
> +    setupTestApiClient()
I think this is requird, there is no before each

2024-10-23 08:44 UTC, james-baker-moj commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactController.kt
> +    description = "Update an contact",
minor grammar, should be "a" instead of "an"

2024-10-23 08:44 UTC, james-baker-moj commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchContactIntegrationTest.kt
> +    setupTestApiClient()
it's not required. remove it and it'll work same as all the others. H2IntegrationTestBase and PostgresIntegrationTestBase both extend the same class IntegrationTestBase. If you "find usages" you'll see this and the base class is the only place it's used (it could be private even maybe?).

2024-10-23 08:44 UTC, james-baker-moj commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchContactIntegrationTest.kt
> +    val existingContact = testAPIClient.getContact(1)
I'm a bit concerned this might impact other tests as the migrations are only run once on spring boot startup as far as I know and aren't reset for every test?
All the other tests that do updates do so on newly created contacts AFAIK. 
I appreciate it's not as easy as you can't set the language code on create. I think it might be better to do multiple updates in the same test (set it to a value and then another with undefined and check the value is still set).

2024-10-23 08:44 UTC, james-baker-moj commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchContactIntegrationTest.kt
> +    val existingContact = testAPIClient.getContact(2)
Same with this test

2024-10-23 08:44 UTC, james-baker-moj commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPatchServiceTest.kt
> +  fun mapToResponse(request: PatchContactRequest, existingContact: ContactEntity): PatchContactResponse {
do all these functions need to be public?

2024-10-23 08:44 UTC, james-baker-moj commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPatchServiceTest.kt
> +      org.junit.jupiter.api.assertThrows<EntityNotFoundException> {
import?

2024-10-23 08:44 UTC, james-baker-moj commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPatchServiceTest.kt
> +  fun mapToEntity(request: PatchContactRequest, existingContact: ContactEntity): ContactEntity {
In fact, as they are all only used once I'd just inline them for readability in the test.

2024-10-23 08:44 UTC, james-baker-moj commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPatchServiceTest.kt
> +      assertThat(updatedContact.languageCode).isEqualTo(null)
`isNull`

2024-10-23 10:06 UTC, prabash-moj commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchContactIntegrationTest.kt
> +    val existingContact = testAPIClient.getContact(1)
This is causing confusion because of BeforeAll and beforeEach order of the lifecycle sequence, I will try to remove this duplication, May be use sql insert statement using JDBC template or something to create the contact , That would also resolve the data leak or unexpected results due to updated data on the h2 db.

2024-10-23 13:17 UTC, james-baker-moj approved these changes
LGTM

2024-10-23 13:19 UTC, merged